// <auto-generated />
using KalashnikovDV_KT_43_21.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KalashnikovDV_KT_43_21.Migrations
{
    [DbContext(typeof(InstitutDbContext))]
    partial class InstitutDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KalashnikovDV_KT_43_21.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("department_id")
                        .HasComment("Идентификатор записи кафедры");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_department_name");

                    b.Property<int>("HeadTeacherID")
                        .HasColumnType("int4")
                        .HasColumnName("c_headteacher_id");

                    b.HasKey("DepartmentId")
                        .HasName("pk_cd_department_department_id");

                    b.HasIndex("HeadTeacherID")
                        .IsUnique();

                    b.HasIndex(new[] { "HeadTeacherID" }, "idx_cd_department_fk_f_headteacher_id");

                    b.ToTable("cd_department", (string)null);
                });

            modelBuilder.Entity("KalashnikovDV_KT_43_21.Models.Disciplines", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("discipline_id")
                        .HasComment("Идентификатор записи дисциплины");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int4")
                        .HasColumnName("c_teacher_id");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_department_name");

                    b.HasKey("DisciplineId")
                        .HasName("pk_cd_disciplines_department_id");

                    b.HasIndex(new[] { "DepartmentId" }, "idx_cd_disciplines_fk_f_department_id");

                    b.ToTable("cd_disciplines", (string)null);
                });

            modelBuilder.Entity("KalashnikovDV_KT_43_21.Models.Teachers", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id")
                        .HasComment("Идентификатор записи преподавателя");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_teacher_firstname")
                        .HasComment("Имя преподавателя");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_teacher_lastname")
                        .HasComment("Отчество преподавателя");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_teacher_secondname")
                        .HasComment("Фамилия преподавателя");

                    b.HasKey("TeacherId")
                        .HasName("pk_cd_teachers_teacher_id");

                    b.ToTable("cd_teachers", (string)null);
                });

            modelBuilder.Entity("KalashnikovDV_KT_43_21.Models.Department", b =>
                {
                    b.HasOne("KalashnikovDV_KT_43_21.Models.Disciplines", null)
                        .WithOne("Department")
                        .HasForeignKey("KalashnikovDV_KT_43_21.Models.Department", "DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_f_department_id");

                    b.HasOne("KalashnikovDV_KT_43_21.Models.Teachers", "Teacher")
                        .WithOne()
                        .HasForeignKey("KalashnikovDV_KT_43_21.Models.Department", "HeadTeacherID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_f_headteacher_id");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("KalashnikovDV_KT_43_21.Models.Disciplines", b =>
                {
                    b.Navigation("Department")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
